name: Docker Build and Push Image to Docker Hub

on:  
  push:    
    branches: [ master ]  
jobs:   
  build:    
    runs-on: ubuntu-18.04                
    steps:    
    - name: Checkout code       
      uses: actions/checkout@v1  

    - name: Set up Docker Buildx      
      uses: crazy-max/ghaction-docker-buildx@v1      
      with:        
        version: latest

    - name: Docker Login      
      if: success()      
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Run Buildx and push image      
      if: success()      
      run: docker buildx build --platform linux/arm/v7 --tag ${{ secrets.DOCKER_USER }}/flask-python-ex-armv7:latest --file ./Dockerfile --output type=image,push=true .